<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Find jobs</name>
   <tag></tag>
   <elementGuidId>68b8d434-d9ad-4e21-8849-f0e5ee69f4da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.yosegi-InlineWhatWhere-primaryButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>97c91eaa-6d5c-42d8-975c-f0f9659a17fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>yosegi-InlineWhatWhere-primaryButton</value>
      <webElementGuid>a8e9b8d9-4276-4605-abcb-3e5a9c33fbdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>7beef5d6-6c38-4d17-91d7-f349958bffb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Find jobs</value>
      <webElementGuid>4cbb9896-0c86-4962-a63f-894e53d94e99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jobsearch&quot;)/button[@class=&quot;yosegi-InlineWhatWhere-primaryButton&quot;]</value>
      <webElementGuid>c1644ab4-3c72-468a-b960-4e6651a46dfc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>73b74727-eff1-4701-9b0e-3631f4c654e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='jobsearch']/button</value>
      <webElementGuid>5d4d6b2f-577f-4a11-8905-caf9f61fb77c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Where'])[1]/following::button[1]</value>
      <webElementGuid>effcb646-e489-4386-b599-58430a84e57b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What'])[1]/following::button[1]</value>
      <webElementGuid>0cc0199d-9fdc-41f8-9b70-dad4d557abbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Post your resume'])[1]/preceding::button[1]</value>
      <webElementGuid>c772ca06-fe53-45fb-8136-e6e62059b312</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='–'])[1]/preceding::button[1]</value>
      <webElementGuid>0d90a9d8-fca6-4235-87ea-1670f0060590</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button</value>
      <webElementGuid>968a8a57-e75f-4955-8d52-aa459db04308</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Find jobs' or . = 'Find jobs')]</value>
      <webElementGuid>dcd50155-147c-46b9-97cf-e41c22ae89ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
